-- Delete the pod-lifecycle telemetry that used to be appended to
-- knowledge_journal on every pod phase transition (core's applyPodEvent,
-- removed in the same change as this migration).
--
-- These rows were ~80% of the table and had no reader: no dashboard view
-- calls GetJournal, no session ever searched for one, and the live value they
-- duplicate is sessions.pod_phase — written by the very same function — with
-- the history in Loki. knowledge_journal is what a future session needs to
-- know about a repo; leaving four rows of pod noise per row of signal made
-- the honest query ("what did sessions learn last week") unusable.
--
-- This DELETE is a deliberate exception to the append-only property recorded
-- in docs/DECISIONS.md — see docs/adr/0054. It is not reversible.
DELETE FROM knowledge_journal WHERE event_type LIKE 'pod.%';
